version: "3"

services:
  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEFAULT_THEME', 'no-theme');
    volumes:
      - wordpress-vol:/var/www/html

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.27.4-alpine@sha256:b471bb609adc83f73c2d95148cf1bd683408739a3c09c0afc666ea2af0037aef
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - wordpress-vol:/var/www/html
      - ./nginx:/etc/nginx/conf.d

volumes:
  wordpress-vol:
